development:
  adapter: postgresql
  database: city_skills_development
  encoding: UTF8
  username: city_skills
  password: city_skills
  port: 5432
  host: localhost
  min_messages: warning


test:
  adapter: postgresql
  database: city_skills_test
  encoding: UTF8
  username: city_skills
  password: city_skills
  port: 5432
  host: localhost
  min_messages: warning
